server {
  listen 80;
  root /usr/share/nginx/html;
  charset utf-8;
  charset_types text/plain text/markdown text/css application/javascript;
  include /etc/nginx/mime.types;
  types { text/plain md yaml sh; }
  location /files/ { autoindex on; }
  location / { try_files $uri $uri/ =404; }
}
